# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change  
  

after_success:
  - Rscript -e 'library(covr); codecov()'
